version: '3'

services:
  webserver:
    container_name: nomi
    image: csunmetalab/environment:nomi
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/
  composer:
    image: composer:latest
    command: install
    volumes:
      - .:/app/